# Red wine Data

In [1]:
# importing required libraries
import pandas as pd
import numpy as np

In [2]:
# loading the data
rw = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/winequality-red.csv')

In [3]:
# loading the dataframe
rw

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [4]:
# seeing the columns
rw.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [5]:
# checking if the null value present in dataset
rw.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
# from above visualization we can see that there is no null value present in dataset

In [7]:
# seeing the types of data present in columns
rw.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [8]:
# checking the shape of data
rw.shape

(1599, 12)

In [14]:
# seeing the different measurements of data
rw.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [20]:
# implementing the machine learning algorithm
# starting with the normalization
def normalize(wine):
    result=wine.copy()
    for feature_name in win.columns:
        max_value=wine[feature_name].max()
        min_value=wine[feature_name].min()
        result[feature_name]=(wine[feature_name]-min_value)/(max_value-min_value)
        return result
    
    red=normalize(redwine)
    
    red.head()

In [21]:
# importing some more required libraries
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [24]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
# implimenting classification model
x=rw.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]].values
y=rw.iloc[:,11].values

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

# classifing the variables using logistic regression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

accuracy=accuracy_score(y_test,y_pred)

print(accuracy)

0.62


In [26]:
# seeing the confusion matrix
# importing the required library
from sklearn.metrics import confusion_matrix

In [27]:
confusion = confusion_matrix(y_test,y_pred)
print(confusion)

[[  0   0   2   0   0   0]
 [  0   0   8   6   0   0]
 [  0   0 130  39   0   0]
 [  0   0  52 118   0   0]
 [  0   0   3  37   0   0]
 [  0   0   0   4   1   0]]


In [28]:
# as we can see that the accuracy is giving 0.62 i.e it is about 62% accurate and it is not much accurate 
# trying to increase its accuracy

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
from sklearn.neural_network import MLPClassifier

In [39]:
model=MLPClassifier(hidden_layer_sizes=(200,100),max_iter=1000)
model.fit(x,y)
predicted_class=model.predict(x_test)
accuracy=accuracy_score(y_test,predicted_class)
print(accuracy)

0.65


In [40]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test,y_pred)
print(confusion)

[[  0   0   2   0   0   0]
 [  0   0   8   6   0   0]
 [  0   0 130  39   0   0]
 [  0   0  52 118   0   0]
 [  0   0   3  37   0   0]
 [  0   0   0   4   1   0]]


In [41]:
from sklearn.metrics import classification_report

In [45]:
report=classification_report(y_test,predicted_class)
print(report)

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       1.00      0.14      0.25        14
           5       0.64      0.88      0.74       169
           6       0.66      0.58      0.62       170
           7       0.69      0.28      0.39        40
           8       0.00      0.00      0.00         5

    accuracy                           0.65       400
   macro avg       0.50      0.31      0.33       400
weighted avg       0.65      0.65      0.62       400



In [49]:
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler(feature_range=(0,1),copy=True)
minmax=MinMaxScaler(feature_range=(0,1),copy=True)

rw=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/winequality-red.csv')
rw

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [51]:
# transforming full data to minmax
scale=minmax.fit_transform(rw)

x = rw.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]].values
y = rw.iloc[:,11].values

y = np.reshape(y,newshape = (-1,1))
x = minmax.fit_transform(x)
print(x)

np.asarray(x,dtype=float)

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.25,random_state=0)

scalar=MLPClassifier(hidden_layer_sizes=(200,100),max_iter=1000)

print(scalar.fit(x,y))

spc=scalar.predict(X_test)
print(spc)

asc = accuracy_score(Y_test,spc)
print(asc)


[[0.24778761 0.39726027 0.         ... 0.60629921 0.13772455 0.15384615]
 [0.28318584 0.52054795 0.         ... 0.36220472 0.20958084 0.21538462]
 [0.28318584 0.43835616 0.04       ... 0.40944882 0.19161677 0.21538462]
 ...
 [0.15044248 0.26712329 0.13       ... 0.53543307 0.25149701 0.4       ]
 [0.11504425 0.35958904 0.12       ... 0.65354331 0.22754491 0.27692308]
 [0.12389381 0.13013699 0.47       ... 0.51181102 0.19760479 0.4       ]]
MLPClassifier(hidden_layer_sizes=(200, 100), max_iter=1000)
[6 5 7 5 5 6 5 6 5 5 5 6 6 5 5 6 7 5 5 5 7 5 6 4 6 5 5 7 5 6 6 6 6 5 7 6 5
 6 6 6 5 7 6 6 6 5 5 6 5 6 5 5 6 6 6 5 5 5 7 6 5 6 6 6 5 6 5 5 7 6 5 6 5 5
 6 6 5 5 5 6 5 5 6 6 6 5 6 5 6 5 5 5 4 5 7 5 7 5 6 5 7 6 6 6 5 5 5 5 6 5 6
 5 7 5 6 6 6 7 6 6 5 7 5 5 6 7 5 5 5 7 5 5 6 6 6 5 6 5 8 5 6 5 5 6 4 6 7 7
 6 5 6 5 5 5 6 6 5 5 6 6 6 6 6 5 5 5 6 6 6 6 7 5 5 7 5 6 6 7 7 5 5 7 6 6 6
 5 6 6 5 5 7 5 6 6 5 5 5 5 6 5 5 6 6 6 5 5 5 6 6 6 5 6 5 5 5 6 5 6 6 5 5 6
 6 6 6 6 6 6 3 5 5 6 6 6 7 6 6 7 6 6 6 6 5 5 6